services:
  - type: web
    name: eventhub-backend
    env: python
    plan: free
    workingDirectory: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application --chdir backend --bind 0.0.0.0:$PORT
